---
title: "ProblemSet2"
author: "Ke-li Chiu & Diego Mamanche Castellanos"
date: "04/02/2020"
output: html_document
abstract: "Abstract asdadfadgd"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
# installing packages

#my_packages <- c("opendatatoronto", "dplyr", "ggplot2", "tidyr")

# For each of the 3 packages, check whether each one exists, and install if not
#for (pkg in my_packages) {
  
#  if (!pkg %in% installed.packages()) { 
    # If package is not installed, install it:
#    install.packages(pkg)
#  } 
#}

# Importing libraries
library(opendatatoronto)
library(dplyr)
library(tidyr)
library(ggplot2)

```

# ABOUT THE DATA


```{r, echo= FALSE}
# Search packages (this returns a table)
wellbeing_packages <- search_packages("Wellbeing")

# Print the table
wellbeing_packages

```



## The Wellbeing Toronto datasets

Explanation



```{r, echo= FALSE}
### Filtering the wellbeing demographic dataset
wellbeing_health_package<- wellbeing_packages %>%
  filter(title == "Wellbeing Toronto - Health") # Only keep the row(s) where the title is "Wellbeing Toronto - Demographics: NHS Indicators"
wellbeing_health_package
```

List the names of the internal datasets

```{r, echo= FALSE}
list_package_resources(wellbeing_health_package)

```

## First dataset

We chose demographics-nhs-indicators-2011 internal dataset for information about income

```{r, echo= FALSE}
#Getting the information dataset called "demographics-nhs-indicators-2011"
health_indicators2011 <- wellbeing_health_package %>% # Start with the package 
  list_package_resources() %>% # List the resources in the package
  filter(name == "wellbeing-toronto-health") %>% # Only keep the resource we want 
  get_resource()
#Select only the sheet `RawData-Ref Period 2011`
health_indicators2011 <- health_indicators2011$`RawData-Ref Period 2011`
health_indicators2011
```
```{r}
#Take the first row as column names
colnames(health_indicators2011) <- health_indicators2011[1:1,]
#Remove the fisrt row
health_indicators2011 <- health_indicators2011[2:141,]

health_indicators2011

```




citation()
citation("tidyverse")

